// prisma/seed/accounting-chart-of-accounts.ts
// Plan de Cuentas NIIF para PYMES Honduras (~200 cuentas)
//
// Estructura por niveles:
//   Nivel 1 (1 dígito):  Cuenta Raíz  — isParent=true, allowDirectEntry=false
//   Nivel 2 (2 dígitos): Sección      — isParent=true, allowDirectEntry=false
//   Nivel 3 (3 dígitos): Grupo        — isParent=true, allowDirectEntry=false
//   Nivel 4 (4 dígitos): Subcuenta    — isParent según tenga hijos
//   Nivel 5 (6 dígitos): Cuenta Hoja  — isParent=false, allowDirectEntry=true
//
// Convención de códigos:
//   Los códigos son numéricos simples; la jerarquía se determina por parentCode
//   (no por prefijo del código). Esto permite flexibilidad en el catálogo NIIF.
//
// Convención de naturaleza:
//   ASSET, COST, EXPENSE → DEBIT    (naturaleza deudora)
//   LIABILITY, EQUITY, INCOME → CREDIT (naturaleza acreedora)
//   CONTRA depende del elemento que contrraresta (marcado explícitamente)

import type { AccountNature, AccountType, PrismaClient } from '@prisma/client';

// ─── Tipo de entrada cruda del catálogo ─────────────────────────────────────

interface AccountEntry {
  code: string;
  parentCode: string | null;
  name: string;
  accountType: AccountType;
  accountNature: AccountNature;
  description?: string;
}

// ─── Catálogo ────────────────────────────────────────────────────────────────

const CHART_OF_ACCOUNTS: AccountEntry[] = [
  // ===========================================================================
  // 1 — ACTIVOS
  // ===========================================================================
  { code: '1', parentCode: null, name: 'ACTIVOS', accountType: 'ASSET', accountNature: 'DEBIT' },

  // 1.1 Activo Corriente
  {
    code: '11',
    parentCode: '1',
    name: 'Activo Corriente',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },

  // 1.1.1 Efectivo y Equivalentes
  {
    code: '111',
    parentCode: '11',
    name: 'Efectivo y Equivalentes de Efectivo',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  { code: '1111', parentCode: '111', name: 'Caja', accountType: 'ASSET', accountNature: 'DEBIT' },
  {
    code: '111101',
    parentCode: '1111',
    name: 'Caja General',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '111102',
    parentCode: '1111',
    name: 'Caja Chica',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1112',
    parentCode: '111',
    name: 'Bancos Nacionales',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '111201',
    parentCode: '1112',
    name: 'Banco Atlántida - Cta. Cte. HNL',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '111202',
    parentCode: '1112',
    name: 'Banco Ficohsa - Cta. Cte. HNL',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '111203',
    parentCode: '1112',
    name: 'Banco de Occidente - Cta. Cte. HNL',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1113',
    parentCode: '111',
    name: 'Bancos Extranjeros',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '111301',
    parentCode: '1113',
    name: 'Banco - Cuenta USD',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },

  // 1.1.2 Inversiones Temporales
  {
    code: '112',
    parentCode: '11',
    name: 'Inversiones a Corto Plazo',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1121',
    parentCode: '112',
    name: 'Certificados de Depósito',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '112101',
    parentCode: '1121',
    name: 'Certificados de Depósito - HNL',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '112102',
    parentCode: '1121',
    name: 'Certificados de Depósito - USD',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1122',
    parentCode: '112',
    name: 'Valores Negociables',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '112201',
    parentCode: '1122',
    name: 'Valores Negociables - Bolsa Hondureña',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },

  // 1.1.3 Cuentas por Cobrar Comerciales
  {
    code: '113',
    parentCode: '11',
    name: 'Cuentas por Cobrar Comerciales',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1131',
    parentCode: '113',
    name: 'Clientes Nacionales',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '113101',
    parentCode: '1131',
    name: 'Clientes Nacionales - Facturas',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1132',
    parentCode: '113',
    name: 'Clientes Extranjeros',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '113201',
    parentCode: '1132',
    name: 'Clientes Extranjeros - USD',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1133',
    parentCode: '113',
    name: 'Estimación para Cuentas Incobrables',
    accountType: 'CONTRA',
    accountNature: 'CREDIT',
    description: 'Contra-activo: reduce el saldo de cuentas por cobrar',
  },

  // 1.1.4 Otras Cuentas por Cobrar
  {
    code: '114',
    parentCode: '11',
    name: 'Otras Cuentas por Cobrar',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1141',
    parentCode: '114',
    name: 'Préstamos a Empleados',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '114101',
    parentCode: '1141',
    name: 'Préstamos a Empleados - Corto Plazo',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1142',
    parentCode: '114',
    name: 'Anticipos a Proveedores',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '114201',
    parentCode: '1142',
    name: 'Anticipos a Proveedores - Mercancía',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '114202',
    parentCode: '1142',
    name: 'Anticipos a Proveedores - Servicios',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1143',
    parentCode: '114',
    name: 'Cuentas por Cobrar a Socios',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '114301',
    parentCode: '1143',
    name: 'Préstamos a Socios - Corto Plazo',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },

  // 1.1.5 Inventarios
  {
    code: '115',
    parentCode: '11',
    name: 'Inventarios',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1151',
    parentCode: '115',
    name: 'Inventario de Mercaderías',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '115101',
    parentCode: '1151',
    name: 'Mercaderías para la Venta',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1152',
    parentCode: '115',
    name: 'Inventario de Materias Primas',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '115201',
    parentCode: '1152',
    name: 'Materias Primas - Nacionales',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '115202',
    parentCode: '1152',
    name: 'Materias Primas - Importadas',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1153',
    parentCode: '115',
    name: 'Inventario de Productos en Proceso',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '115301',
    parentCode: '1153',
    name: 'Productos en Proceso',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1154',
    parentCode: '115',
    name: 'Inventario de Productos Terminados',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '115401',
    parentCode: '1154',
    name: 'Productos Terminados - Almacén Central',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1155',
    parentCode: '115',
    name: 'Materiales y Suministros',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '115501',
    parentCode: '1155',
    name: 'Materiales de Empaque',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '115502',
    parentCode: '1155',
    name: 'Suministros de Mantenimiento',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },

  // 1.1.6 Gastos Pagados por Anticipado
  {
    code: '116',
    parentCode: '11',
    name: 'Gastos Pagados por Anticipado',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1161',
    parentCode: '116',
    name: 'Seguros Pagados por Anticipado',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '116101',
    parentCode: '1161',
    name: 'Seguros - Vehículos',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '116102',
    parentCode: '1161',
    name: 'Seguros - Edificios',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1162',
    parentCode: '116',
    name: 'Alquileres Pagados por Anticipado',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '116201',
    parentCode: '1162',
    name: 'Alquiler de Local - Anticipado',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1163',
    parentCode: '116',
    name: 'Publicidad Pagada por Anticipado',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '116301',
    parentCode: '1163',
    name: 'Publicidad y Mercadeo - Anticipado',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1164',
    parentCode: '116',
    name: 'Papelería y Útiles',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '116401',
    parentCode: '1164',
    name: 'Papelería y Útiles de Oficina',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },

  // 1.1.7 Impuestos por Acreditar
  {
    code: '117',
    parentCode: '11',
    name: 'Impuestos por Acreditar',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1171',
    parentCode: '117',
    name: 'ISV por Acreditar (Crédito Fiscal)',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '117101',
    parentCode: '1171',
    name: 'ISV 15% por Acreditar',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '117102',
    parentCode: '1171',
    name: 'ISV 18% por Acreditar',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1172',
    parentCode: '117',
    name: 'Pagos a Cuenta ISR',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '117201',
    parentCode: '1172',
    name: 'Pagos a Cuenta ISR - Ejercicio Actual',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },

  // ─── 1.2 Activo No Corriente ────────────────────────────────────────────────
  {
    code: '12',
    parentCode: '1',
    name: 'Activo No Corriente',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },

  // 1.2.1 Inversiones a Largo Plazo
  {
    code: '121',
    parentCode: '12',
    name: 'Inversiones a Largo Plazo',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1211',
    parentCode: '121',
    name: 'Inversiones en Subsidiarias',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '121101',
    parentCode: '1211',
    name: 'Participación en Subsidiarias',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1212',
    parentCode: '121',
    name: 'Otras Inversiones a Largo Plazo',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '121201',
    parentCode: '1212',
    name: 'Inversiones en Bonos del Estado',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },

  // 1.2.2 Propiedades, Planta y Equipo
  // Nota: cada tipo de activo lleva su (-) Depreciación Acumulada como subcuenta
  {
    code: '122',
    parentCode: '12',
    name: 'Propiedades, Planta y Equipo',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1221',
    parentCode: '122',
    name: 'Terrenos',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '122101',
    parentCode: '1221',
    name: 'Terrenos - Valor de Adquisición',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1222',
    parentCode: '122',
    name: 'Edificios e Instalaciones',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '122201',
    parentCode: '1222',
    name: 'Edificios - Valor de Adquisición',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '122202',
    parentCode: '1222',
    name: 'Instalaciones y Mejoras',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '122203',
    parentCode: '1222',
    name: '(-) Depreciación Acumulada - Edificios',
    accountType: 'CONTRA',
    accountNature: 'CREDIT',
    description: 'Contra-activo de edificios e instalaciones',
  },
  {
    code: '1223',
    parentCode: '122',
    name: 'Mobiliario y Equipo de Oficina',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '122301',
    parentCode: '1223',
    name: 'Mobiliario de Oficina',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '122302',
    parentCode: '1223',
    name: 'Equipo de Oficina',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '122303',
    parentCode: '1223',
    name: '(-) Depreciación Acumulada - Mobiliario',
    accountType: 'CONTRA',
    accountNature: 'CREDIT',
    description: 'Contra-activo de mobiliario y equipo de oficina',
  },
  {
    code: '1224',
    parentCode: '122',
    name: 'Equipo de Cómputo',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '122401',
    parentCode: '1224',
    name: 'Computadoras y Servidores',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '122402',
    parentCode: '1224',
    name: 'Equipos de Comunicación y Red',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '122403',
    parentCode: '1224',
    name: '(-) Depreciación Acumulada - Equipo de Cómputo',
    accountType: 'CONTRA',
    accountNature: 'CREDIT',
    description: 'Contra-activo de equipo de cómputo',
  },
  {
    code: '1225',
    parentCode: '122',
    name: 'Vehículos',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '122501',
    parentCode: '1225',
    name: 'Vehículos de Transporte',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '122502',
    parentCode: '1225',
    name: 'Vehículos de Carga',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '122503',
    parentCode: '1225',
    name: '(-) Depreciación Acumulada - Vehículos',
    accountType: 'CONTRA',
    accountNature: 'CREDIT',
    description: 'Contra-activo de vehículos',
  },
  {
    code: '1226',
    parentCode: '122',
    name: 'Maquinaria y Equipo Industrial',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '122601',
    parentCode: '1226',
    name: 'Maquinaria Industrial',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '122602',
    parentCode: '1226',
    name: '(-) Depreciación Acumulada - Maquinaria',
    accountType: 'CONTRA',
    accountNature: 'CREDIT',
    description: 'Contra-activo de maquinaria y equipo industrial',
  },

  // 1.2.3 Activos Intangibles
  {
    code: '123',
    parentCode: '12',
    name: 'Activos Intangibles',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1231',
    parentCode: '123',
    name: 'Licencias y Software',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '123101',
    parentCode: '1231',
    name: 'Licencias de Software',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '123102',
    parentCode: '1231',
    name: 'Desarrollo de Software Propio',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1232',
    parentCode: '123',
    name: 'Marcas, Patentes y Franquicias',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '123201',
    parentCode: '1232',
    name: 'Marcas Registradas',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1233',
    parentCode: '123',
    name: '(-) Amortización Acumulada - Intangibles',
    accountType: 'CONTRA',
    accountNature: 'CREDIT',
    description: 'Contra-activo de intangibles amortizables',
  },

  // 1.2.4 Otros Activos No Corrientes
  {
    code: '124',
    parentCode: '12',
    name: 'Otros Activos No Corrientes',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1241',
    parentCode: '124',
    name: 'Depósitos en Garantía',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '124101',
    parentCode: '1241',
    name: 'Depósito de Arrendamiento',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '1242',
    parentCode: '124',
    name: 'Activos por Impuesto Diferido',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },
  {
    code: '124201',
    parentCode: '1242',
    name: 'Activo Fiscal Diferido - ISR',
    accountType: 'ASSET',
    accountNature: 'DEBIT',
  },

  // ===========================================================================
  // 2 — PASIVOS
  // ===========================================================================
  {
    code: '2',
    parentCode: null,
    name: 'PASIVOS',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },

  // 2.1 Pasivo Corriente
  {
    code: '21',
    parentCode: '2',
    name: 'Pasivo Corriente',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },

  // 2.1.1 Cuentas por Pagar Comerciales
  {
    code: '211',
    parentCode: '21',
    name: 'Cuentas por Pagar Comerciales',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2111',
    parentCode: '211',
    name: 'Proveedores Nacionales',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '211101',
    parentCode: '2111',
    name: 'Proveedores Nacionales - Facturas',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2112',
    parentCode: '211',
    name: 'Proveedores Extranjeros',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '211201',
    parentCode: '2112',
    name: 'Proveedores Extranjeros - USD',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },

  // 2.1.2 Préstamos y Sobregiros Bancarios
  {
    code: '212',
    parentCode: '21',
    name: 'Préstamos y Sobregiros Bancarios',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2121',
    parentCode: '212',
    name: 'Préstamos Bancarios a Corto Plazo',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '212101',
    parentCode: '2121',
    name: 'Préstamo Bancario - Corto Plazo HNL',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '212102',
    parentCode: '2121',
    name: 'Préstamo Bancario - Corto Plazo USD',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2122',
    parentCode: '212',
    name: 'Porción Corriente de Deuda a Largo Plazo',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '212201',
    parentCode: '2122',
    name: 'Porción Corriente - Hipotecas',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2123',
    parentCode: '212',
    name: 'Sobregiros Bancarios',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '212301',
    parentCode: '2123',
    name: 'Sobregiro - Cuenta Corriente',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },

  // 2.1.3 Impuestos por Pagar
  {
    code: '213',
    parentCode: '21',
    name: 'Impuestos por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2131',
    parentCode: '213',
    name: 'ISV por Pagar (Débito Fiscal)',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '213101',
    parentCode: '2131',
    name: 'ISV Débito Fiscal 15%',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '213102',
    parentCode: '2131',
    name: 'ISV Débito Fiscal 18%',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2132',
    parentCode: '213',
    name: 'Impuesto sobre la Renta por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '213201',
    parentCode: '2132',
    name: 'ISR Empresarial por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2133',
    parentCode: '213',
    name: 'Retenciones ISR por Enterar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '213301',
    parentCode: '2133',
    name: 'ISR Retenido - Honorarios',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '213302',
    parentCode: '2133',
    name: 'ISR Retenido - Alquileres',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2134',
    parentCode: '213',
    name: 'Impuesto sobre Activos Netos (ISAN)',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '213401',
    parentCode: '2134',
    name: 'ISAN por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },

  // 2.1.4 Otras Cuentas y Documentos por Pagar
  {
    code: '214',
    parentCode: '21',
    name: 'Otras Cuentas y Documentos por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2141',
    parentCode: '214',
    name: 'Anticipos de Clientes',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '214101',
    parentCode: '2141',
    name: 'Anticipos de Clientes - Servicios',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '214102',
    parentCode: '2141',
    name: 'Anticipos de Clientes - Mercadería',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2142',
    parentCode: '214',
    name: 'Documentos por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '214201',
    parentCode: '2142',
    name: 'Pagarés por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2143',
    parentCode: '214',
    name: 'Dividendos por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '214301',
    parentCode: '2143',
    name: 'Dividendos Decretados por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },

  // 2.1.5 Gastos Acumulados por Pagar (nómina y beneficios Honduras)
  {
    code: '215',
    parentCode: '21',
    name: 'Gastos Acumulados por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2151',
    parentCode: '215',
    name: 'Sueldos y Salarios por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '215101',
    parentCode: '2151',
    name: 'Salarios por Pagar - Quincena',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2152',
    parentCode: '215',
    name: 'Beneficios a Empleados por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '215201',
    parentCode: '2152',
    name: 'Décimo Cuarto Mes Acumulado',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
    description: '13vo mes — se paga en junio (Art. 342 Código del Trabajo Honduras)',
  },
  {
    code: '215202',
    parentCode: '2152',
    name: 'Décimo Quinto Mes Acumulado',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
    description: '14vo mes — se paga en diciembre (Navidad)',
  },
  {
    code: '215203',
    parentCode: '2152',
    name: 'Vacaciones Acumuladas por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '215204',
    parentCode: '2152',
    name: 'Cesantía Acumulada por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2153',
    parentCode: '215',
    name: 'Seguridad Social y Fondos de Pensiones',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '215301',
    parentCode: '2153',
    name: 'IHSS Patronal por Enterar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
    description: 'Instituto Hondureño de Seguridad Social - aporte patronal',
  },
  {
    code: '215302',
    parentCode: '2153',
    name: 'RAP Patronal por Enterar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
    description: 'Régimen de Aportaciones Privadas - aporte patronal 1.5%',
  },
  {
    code: '215303',
    parentCode: '2153',
    name: 'INFOP por Enterar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
    description: 'Instituto Nacional de Formación Profesional - 1% planilla',
  },
  {
    code: '2154',
    parentCode: '215',
    name: 'Retenciones Laborales por Enterar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '215401',
    parentCode: '2154',
    name: 'IHSS Retenido al Empleado',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '215402',
    parentCode: '2154',
    name: 'RAP Retenido al Empleado',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '215403',
    parentCode: '2154',
    name: 'ISR Retenido a Empleados',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2155',
    parentCode: '215',
    name: 'Otros Gastos Acumulados',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '215501',
    parentCode: '2155',
    name: 'Alquileres por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '215502',
    parentCode: '2155',
    name: 'Servicios Públicos por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '215503',
    parentCode: '2155',
    name: 'Honorarios Profesionales por Pagar',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },

  // 2.2 Pasivo No Corriente
  {
    code: '22',
    parentCode: '2',
    name: 'Pasivo No Corriente',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },

  // 2.2.1 Préstamos a Largo Plazo
  {
    code: '221',
    parentCode: '22',
    name: 'Préstamos a Largo Plazo',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2211',
    parentCode: '221',
    name: 'Préstamos Hipotecarios',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '221101',
    parentCode: '2211',
    name: 'Hipoteca - Banco Nacional LP',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2212',
    parentCode: '221',
    name: 'Préstamos de Largo Plazo - Otros',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '221201',
    parentCode: '2212',
    name: 'Préstamo Equipamiento - LP',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },

  // 2.2.2 Beneficios a Empleados LP
  {
    code: '222',
    parentCode: '22',
    name: 'Beneficios a Empleados a Largo Plazo',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2221',
    parentCode: '222',
    name: 'Provisión para Cesantía LP',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '222101',
    parentCode: '2221',
    name: 'Cesantía Acumulada - Largo Plazo',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },

  // 2.2.3 Otros Pasivos No Corrientes
  {
    code: '223',
    parentCode: '22',
    name: 'Otros Pasivos No Corrientes',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '2231',
    parentCode: '223',
    name: 'Pasivos por Impuesto Diferido',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },
  {
    code: '223101',
    parentCode: '2231',
    name: 'Pasivo Fiscal Diferido - ISR',
    accountType: 'LIABILITY',
    accountNature: 'CREDIT',
  },

  // ===========================================================================
  // 3 — PATRIMONIO
  // ===========================================================================
  {
    code: '3',
    parentCode: null,
    name: 'PATRIMONIO',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },

  // 3.1 Capital Social
  {
    code: '31',
    parentCode: '3',
    name: 'Capital Social',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '311',
    parentCode: '31',
    name: 'Capital Pagado',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '3111',
    parentCode: '311',
    name: 'Capital Social Suscrito y Pagado',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '311101',
    parentCode: '3111',
    name: 'Acciones Comunes Pagadas',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '311102',
    parentCode: '3111',
    name: 'Capital de Aportación (Empresa no Societaria)',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '312',
    parentCode: '31',
    name: 'Prima en Emisión de Acciones',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '3121',
    parentCode: '312',
    name: 'Superávit por Prima en Acciones',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '312101',
    parentCode: '3121',
    name: 'Prima en Emisión de Acciones Comunes',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },

  // 3.2 Reservas
  { code: '32', parentCode: '3', name: 'Reservas', accountType: 'EQUITY', accountNature: 'CREDIT' },
  {
    code: '321',
    parentCode: '32',
    name: 'Reserva Legal',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '3211',
    parentCode: '321',
    name: 'Reserva Legal Acumulada',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
    description:
      'Reserva Legal obligatoria 5% hasta 25% del capital (Art. 32 C. Comercio Honduras)',
  },
  {
    code: '321101',
    parentCode: '3211',
    name: 'Reserva Legal',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '322',
    parentCode: '32',
    name: 'Otras Reservas',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '3221',
    parentCode: '322',
    name: 'Reservas Estatutarias',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '322101',
    parentCode: '3221',
    name: 'Reserva para Contingencias',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },

  // 3.3 Resultados Acumulados
  {
    code: '33',
    parentCode: '3',
    name: 'Resultados Acumulados',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '331',
    parentCode: '33',
    name: 'Utilidades Retenidas',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '3311',
    parentCode: '331',
    name: 'Utilidades No Distribuidas',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '331101',
    parentCode: '3311',
    name: 'Utilidades Retenidas de Ejercicios Anteriores',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '332',
    parentCode: '33',
    name: 'Déficit Acumulado',
    accountType: 'CONTRA',
    accountNature: 'DEBIT',
    description: 'Contra-patrimonio: pérdidas acumuladas de ejercicios anteriores',
  },
  {
    code: '3321',
    parentCode: '332',
    name: 'Pérdidas Acumuladas',
    accountType: 'CONTRA',
    accountNature: 'DEBIT',
  },
  {
    code: '332101',
    parentCode: '3321',
    name: 'Déficit de Ejercicios Anteriores',
    accountType: 'CONTRA',
    accountNature: 'DEBIT',
  },

  // 3.4 Resultado del Período
  {
    code: '34',
    parentCode: '3',
    name: 'Resultado del Período',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '341',
    parentCode: '34',
    name: 'Utilidad del Período',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '3411',
    parentCode: '341',
    name: 'Utilidad Neta del Ejercicio',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '341101',
    parentCode: '3411',
    name: 'Utilidad del Período Actual',
    accountType: 'EQUITY',
    accountNature: 'CREDIT',
  },
  {
    code: '342',
    parentCode: '34',
    name: 'Pérdida del Período',
    accountType: 'CONTRA',
    accountNature: 'DEBIT',
    description: 'Contra-patrimonio: pérdida neta del ejercicio corriente',
  },
  {
    code: '3421',
    parentCode: '342',
    name: 'Pérdida Neta del Ejercicio',
    accountType: 'CONTRA',
    accountNature: 'DEBIT',
  },
  {
    code: '342101',
    parentCode: '3421',
    name: 'Pérdida del Período Actual',
    accountType: 'CONTRA',
    accountNature: 'DEBIT',
  },

  // ===========================================================================
  // 4 — INGRESOS
  // ===========================================================================
  { code: '4', parentCode: null, name: 'INGRESOS', accountType: 'INCOME', accountNature: 'CREDIT' },

  // 4.1 Ingresos de Operación
  {
    code: '41',
    parentCode: '4',
    name: 'Ingresos de Operación',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  { code: '411', parentCode: '41', name: 'Ventas', accountType: 'INCOME', accountNature: 'CREDIT' },
  {
    code: '4111',
    parentCode: '411',
    name: 'Ventas de Mercaderías',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '411101',
    parentCode: '4111',
    name: 'Ventas Nacionales - Mercaderías',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '411102',
    parentCode: '4111',
    name: 'Ventas Exportación - Mercaderías',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '4112',
    parentCode: '411',
    name: 'Ventas de Servicios',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '411201',
    parentCode: '4112',
    name: 'Servicios Profesionales Cobrados',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '411202',
    parentCode: '4112',
    name: 'Servicios de Mantenimiento',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '4113',
    parentCode: '411',
    name: 'Devoluciones y Descuentos s/Ventas',
    accountType: 'CONTRA',
    accountNature: 'DEBIT',
    description: 'Contra-ingreso: reduce el ingreso por ventas',
  },
  {
    code: '411301',
    parentCode: '4113',
    name: 'Devoluciones sobre Ventas',
    accountType: 'CONTRA',
    accountNature: 'DEBIT',
  },
  {
    code: '411302',
    parentCode: '4113',
    name: 'Descuentos Concedidos a Clientes',
    accountType: 'CONTRA',
    accountNature: 'DEBIT',
  },
  {
    code: '412',
    parentCode: '41',
    name: 'Otros Ingresos de Operación',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '4121',
    parentCode: '412',
    name: 'Comisiones Ganadas',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '412101',
    parentCode: '4121',
    name: 'Comisiones por Intermediación',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '4122',
    parentCode: '412',
    name: 'Alquileres Cobrados',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '412201',
    parentCode: '4122',
    name: 'Ingresos por Arrendamiento',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },

  // 4.2 Ingresos Financieros
  {
    code: '42',
    parentCode: '4',
    name: 'Ingresos Financieros',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '421',
    parentCode: '42',
    name: 'Intereses Ganados',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '4211',
    parentCode: '421',
    name: 'Intereses sobre Inversiones',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '421101',
    parentCode: '4211',
    name: 'Intereses sobre Cuentas de Ahorro',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '421102',
    parentCode: '4211',
    name: 'Intereses sobre Certificados de Depósito',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '422',
    parentCode: '42',
    name: 'Diferencial Cambiario Ganado',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '4221',
    parentCode: '422',
    name: 'Ganancia por Tipo de Cambio',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '422101',
    parentCode: '4221',
    name: 'Diferencial Cambiario USD-HNL Ganado',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },

  // 4.3 Otros Ingresos
  {
    code: '43',
    parentCode: '4',
    name: 'Otros Ingresos',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '431',
    parentCode: '43',
    name: 'Ingresos No Operativos',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '4311',
    parentCode: '431',
    name: 'Utilidad en Venta de Activos',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '431101',
    parentCode: '4311',
    name: 'Ganancia en Venta de Propiedades',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '431102',
    parentCode: '4311',
    name: 'Ganancia en Venta de Equipo',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '4312',
    parentCode: '431',
    name: 'Recuperación de Cuentas Incobrables',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '431201',
    parentCode: '4312',
    name: 'Recuperación de Cartera Castigada',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '4313',
    parentCode: '431',
    name: 'Ingresos Extraordinarios',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },
  {
    code: '431301',
    parentCode: '4313',
    name: 'Otros Ingresos No Recurrentes',
    accountType: 'INCOME',
    accountNature: 'CREDIT',
  },

  // ===========================================================================
  // 5 — COSTOS
  // ===========================================================================
  { code: '5', parentCode: null, name: 'COSTOS', accountType: 'COST', accountNature: 'DEBIT' },

  // 5.1 Costo de Ventas y Servicios
  {
    code: '51',
    parentCode: '5',
    name: 'Costo de Ventas y Servicios',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '511',
    parentCode: '51',
    name: 'Costo de Mercaderías Vendidas',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '5111',
    parentCode: '511',
    name: 'CMV - Ventas Nacionales',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '511101',
    parentCode: '5111',
    name: 'Costo de Mercadería Vendida - Nacional',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '5112',
    parentCode: '511',
    name: 'CMV - Exportaciones',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '511201',
    parentCode: '5112',
    name: 'Costo de Mercadería Exportada',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '512',
    parentCode: '51',
    name: 'Costo de Servicios Prestados',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '5121',
    parentCode: '512',
    name: 'Mano de Obra Directa de Servicios',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '512101',
    parentCode: '5121',
    name: 'Salarios Directos de Servicios',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '5122',
    parentCode: '512',
    name: 'Materiales Directos de Servicios',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '512201',
    parentCode: '5122',
    name: 'Materiales Directos Utilizados',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '5123',
    parentCode: '512',
    name: 'Costos Indirectos de Servicios',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '512301',
    parentCode: '5123',
    name: 'Costos Generales de Prestación',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },

  // 5.2 Costo de Producción
  {
    code: '52',
    parentCode: '5',
    name: 'Costo de Producción',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '521',
    parentCode: '52',
    name: 'Materia Prima Directa',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '5211',
    parentCode: '521',
    name: 'Consumo de Materia Prima',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '521101',
    parentCode: '5211',
    name: 'Materia Prima Nacional Utilizada',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '521102',
    parentCode: '5211',
    name: 'Materia Prima Importada Utilizada',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '522',
    parentCode: '52',
    name: 'Mano de Obra Directa de Producción',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '5221',
    parentCode: '522',
    name: 'Salarios de Producción',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '522101',
    parentCode: '5221',
    name: 'Salarios Directos de Producción',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '523',
    parentCode: '52',
    name: 'Costos Indirectos de Fabricación',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '5231',
    parentCode: '523',
    name: 'CIF - Materiales Indirectos',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '523101',
    parentCode: '5231',
    name: 'Materiales Indirectos Consumidos',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '5232',
    parentCode: '523',
    name: 'CIF - Mano de Obra Indirecta',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '523201',
    parentCode: '5232',
    name: 'Salarios Indirectos de Producción',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '5233',
    parentCode: '523',
    name: 'CIF - Gastos Generales de Fábrica',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '523301',
    parentCode: '5233',
    name: 'Energía Eléctrica - Planta',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },
  {
    code: '523302',
    parentCode: '5233',
    name: 'Depreciación Maquinaria - Producción',
    accountType: 'COST',
    accountNature: 'DEBIT',
  },

  // ===========================================================================
  // 6 — GASTOS
  // ===========================================================================
  { code: '6', parentCode: null, name: 'GASTOS', accountType: 'EXPENSE', accountNature: 'DEBIT' },

  // 6.1 Gastos de Ventas
  {
    code: '61',
    parentCode: '6',
    name: 'Gastos de Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '611',
    parentCode: '61',
    name: 'Gastos de Personal - Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6111',
    parentCode: '611',
    name: 'Remuneraciones - Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '611101',
    parentCode: '6111',
    name: 'Sueldos y Salarios - Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '611102',
    parentCode: '6111',
    name: 'Comisiones sobre Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6112',
    parentCode: '611',
    name: 'Beneficios a Empleados - Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '611201',
    parentCode: '6112',
    name: 'Décimo Cuarto Mes - Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '611202',
    parentCode: '6112',
    name: 'Décimo Quinto Mes - Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '611203',
    parentCode: '6112',
    name: 'Vacaciones - Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '611204',
    parentCode: '6112',
    name: 'Cesantía - Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6113',
    parentCode: '611',
    name: 'Cargas Sociales - Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '611301',
    parentCode: '6113',
    name: 'IHSS Patronal - Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '611302',
    parentCode: '6113',
    name: 'RAP Patronal - Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '611303',
    parentCode: '6113',
    name: 'INFOP - Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '612',
    parentCode: '61',
    name: 'Gastos Operativos - Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6121',
    parentCode: '612',
    name: 'Publicidad y Mercadeo',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '612101',
    parentCode: '6121',
    name: 'Publicidad en Medios',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '612102',
    parentCode: '6121',
    name: 'Material de Mercadeo y POP',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6122',
    parentCode: '612',
    name: 'Transporte y Entregas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '612201',
    parentCode: '6122',
    name: 'Flete y Transporte de Mercadería',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '612202',
    parentCode: '6122',
    name: 'Combustibles - Entregas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6123',
    parentCode: '612',
    name: 'Gastos de Representación - Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '612301',
    parentCode: '6123',
    name: 'Atención a Clientes y Viáticos de Ventas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },

  // 6.2 Gastos de Administración
  {
    code: '62',
    parentCode: '6',
    name: 'Gastos de Administración',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '621',
    parentCode: '62',
    name: 'Gastos de Personal - Administración',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6211',
    parentCode: '621',
    name: 'Remuneraciones - Administración',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '621101',
    parentCode: '6211',
    name: 'Sueldos y Salarios - Administración',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6212',
    parentCode: '621',
    name: 'Beneficios a Empleados - Administración',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '621201',
    parentCode: '6212',
    name: 'Décimo Cuarto Mes - Administración',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '621202',
    parentCode: '6212',
    name: 'Décimo Quinto Mes - Administración',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '621203',
    parentCode: '6212',
    name: 'Vacaciones - Administración',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '621204',
    parentCode: '6212',
    name: 'Cesantía - Administración',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6213',
    parentCode: '621',
    name: 'Cargas Sociales - Administración',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '621301',
    parentCode: '6213',
    name: 'IHSS Patronal - Administración',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '621302',
    parentCode: '6213',
    name: 'RAP Patronal - Administración',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '621303',
    parentCode: '6213',
    name: 'INFOP - Administración',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '622',
    parentCode: '62',
    name: 'Servicios y Suministros - Administración',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6221',
    parentCode: '622',
    name: 'Alquileres',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '622101',
    parentCode: '6221',
    name: 'Alquiler de Oficinas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '622102',
    parentCode: '6221',
    name: 'Alquiler de Bodegas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6222',
    parentCode: '622',
    name: 'Servicios Públicos',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '622201',
    parentCode: '6222',
    name: 'Energía Eléctrica',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '622202',
    parentCode: '6222',
    name: 'Agua y Alcantarillado',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '622203',
    parentCode: '6222',
    name: 'Telecomunicaciones e Internet',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6223',
    parentCode: '622',
    name: 'Papelería y Útiles de Oficina',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '622301',
    parentCode: '6223',
    name: 'Papelería, Útiles y Suministros de Oficina',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6224',
    parentCode: '622',
    name: 'Seguros',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '622401',
    parentCode: '6224',
    name: 'Seguros de Responsabilidad Civil',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '622402',
    parentCode: '6224',
    name: 'Seguros de Vida Colectivo',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6225',
    parentCode: '622',
    name: 'Mantenimiento y Reparaciones',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '622501',
    parentCode: '6225',
    name: 'Mantenimiento de Edificios e Instalaciones',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '622502',
    parentCode: '6225',
    name: 'Mantenimiento de Equipo de Cómputo',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '622503',
    parentCode: '6225',
    name: 'Mantenimiento de Vehículos Administrativos',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '623',
    parentCode: '62',
    name: 'Depreciaciones y Amortizaciones',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6231',
    parentCode: '623',
    name: 'Depreciaciones',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '623101',
    parentCode: '6231',
    name: 'Depreciación de Edificios',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '623102',
    parentCode: '6231',
    name: 'Depreciación de Mobiliario',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '623103',
    parentCode: '6231',
    name: 'Depreciación de Equipo de Cómputo',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '623104',
    parentCode: '6231',
    name: 'Depreciación de Vehículos',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '623105',
    parentCode: '6231',
    name: 'Depreciación de Maquinaria',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6232',
    parentCode: '623',
    name: 'Amortizaciones',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '623201',
    parentCode: '6232',
    name: 'Amortización de Software e Intangibles',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '624',
    parentCode: '62',
    name: 'Otros Gastos de Administración',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6241',
    parentCode: '624',
    name: 'Honorarios Profesionales',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '624101',
    parentCode: '6241',
    name: 'Honorarios de Auditoría',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '624102',
    parentCode: '6241',
    name: 'Honorarios de Asesoría Legal',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '624103',
    parentCode: '6241',
    name: 'Honorarios de Contabilidad Externa',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6242',
    parentCode: '624',
    name: 'Impuestos y Tasas',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '624201',
    parentCode: '6242',
    name: 'Impuesto Industria, Comercio y Servicios',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '624202',
    parentCode: '6242',
    name: 'Tasas Municipales y Permisos',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6243',
    parentCode: '624',
    name: 'Pérdida por Cuentas Incobrables',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '624301',
    parentCode: '6243',
    name: 'Gasto por Deterioro de Cartera',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6244',
    parentCode: '624',
    name: 'Gastos de Viaje y Representación',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '624401',
    parentCode: '6244',
    name: 'Viáticos y Gastos de Viaje Administrativos',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6245',
    parentCode: '624',
    name: 'Combustibles y Lubricantes',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '624501',
    parentCode: '6245',
    name: 'Combustibles - Vehículos Administrativos',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6246',
    parentCode: '624',
    name: 'Donaciones y Responsabilidad Social',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '624601',
    parentCode: '6246',
    name: 'Donaciones a Instituciones sin Fines de Lucro',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6247',
    parentCode: '624',
    name: 'Otros Gastos Administrativos Varios',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '624701',
    parentCode: '6247',
    name: 'Gastos Varios No Clasificados',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },

  // 6.3 Gastos Financieros
  {
    code: '63',
    parentCode: '6',
    name: 'Gastos Financieros',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '631',
    parentCode: '63',
    name: 'Intereses y Cargos Financieros',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6311',
    parentCode: '631',
    name: 'Intereses sobre Préstamos',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '631101',
    parentCode: '6311',
    name: 'Intereses sobre Préstamos Bancarios',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '631102',
    parentCode: '6311',
    name: 'Intereses sobre Arrendamientos Financieros',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6312',
    parentCode: '631',
    name: 'Comisiones y Gastos Bancarios',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '631201',
    parentCode: '6312',
    name: 'Comisiones y Cargos Bancarios',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '632',
    parentCode: '63',
    name: 'Diferencial Cambiario Pérdida',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6321',
    parentCode: '632',
    name: 'Pérdida por Tipo de Cambio',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '632101',
    parentCode: '6321',
    name: 'Diferencial Cambiario USD-HNL Pérdida',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },

  // 6.4 Otros Gastos
  {
    code: '64',
    parentCode: '6',
    name: 'Otros Gastos',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '641',
    parentCode: '64',
    name: 'Gastos No Operativos',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6411',
    parentCode: '641',
    name: 'Pérdida en Venta de Activos',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '641101',
    parentCode: '6411',
    name: 'Pérdida en Venta de Propiedades',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '641102',
    parentCode: '6411',
    name: 'Pérdida en Venta de Equipo',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '6412',
    parentCode: '641',
    name: 'Gastos Extraordinarios',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '641201',
    parentCode: '6412',
    name: 'Pérdidas por Siniestros y Catástrofes',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
  {
    code: '641202',
    parentCode: '6412',
    name: 'Otros Gastos No Recurrentes',
    accountType: 'EXPENSE',
    accountNature: 'DEBIT',
  },
];

// ─── Función principal de seed ───────────────────────────────────────────────

/**
 * Siembra el plan de cuentas NIIF Honduras (~200 cuentas) para una empresa.
 * Idempotente — usa upsert por (companyId, code) para poder re-ejecutar sin duplicar.
 *
 * Estrategia de inserción por niveles:
 *   Ordena por longitud de código (padres primero), luego alfabético.
 *   Construye un map code→id en tiempo de ejecución para resolver parentId.
 */
export async function seedAccountingChartOfAccounts(
  companyId: string,
  prisma: PrismaClient,
): Promise<void> {
  // Determinar qué códigos actúan como padre de algún hijo
  const parentCodes = new Set(
    CHART_OF_ACCOUNTS.map((a) => a.parentCode).filter((c): c is string => c !== null),
  );

  // Map código → UUID asignado en BD (construido durante la inserción)
  const codeToId = new Map<string, string>();

  // Insertar en orden: padres antes que hijos (ordenar por longitud de código)
  const ordered = [...CHART_OF_ACCOUNTS].sort((a, b) => {
    if (a.code.length !== b.code.length) return a.code.length - b.code.length;
    return a.code.localeCompare(b.code);
  });

  for (const entry of ordered) {
    const isParent = parentCodes.has(entry.code);
    const parentId = entry.parentCode ? (codeToId.get(entry.parentCode) ?? null) : null;

    const account = await prisma.account.upsert({
      where: { companyId_code: { companyId, code: entry.code } },
      update: {
        name: entry.name,
        accountType: entry.accountType,
        accountNature: entry.accountNature,
        isParent,
        allowDirectEntry: !isParent,
        description: entry.description ?? null,
        parentId,
      },
      create: {
        companyId,
        code: entry.code,
        name: entry.name,
        accountType: entry.accountType,
        accountNature: entry.accountNature,
        isParent,
        allowDirectEntry: !isParent,
        isActive: true,
        description: entry.description ?? null,
        parentId,
      },
      select: { id: true, code: true },
    });

    codeToId.set(account.code, account.id);
  }

  console.log(
    `✅ Plan de Cuentas NIIF Honduras: ${CHART_OF_ACCOUNTS.length} cuentas procesadas (company: ${companyId})`,
  );
}
